# on changes to the changelog, or any pull request
name: Continuous Integration
on:
  push:
    paths:
      - 'CHANGELOG.md'
  pull_request:
    paths:
      - 'CHANGELOG.md'
jobs:
  PSP:
   runs-on: ubuntu-latest
   container: pspdev/pspdev:latest
   steps:
     - name: Install dependencies
       run: apk add cmake git zip
     - name: Checkout
       uses: actions/checkout@v2
     - name: Build
       run: ./build_psp.sh --package
  
     - name: Extract tag name
       if: startsWith(github.ref, 'refs/tags/')
       id: tag
       run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

     - name: Create release
       uses: softprops/action-gh-release@v1
       with:
        files: build/psp/*.zip
        body: |
          This is an automated release of the latest version of UNTITLED-PSP.
        prerelease: true
        tag_name: ${{ steps.tag.outputs.VERSION }}
        name: Untitled ${{ steps.tag.outputs.VERSION }}
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



